### ISSUE TITLE
Download Images?

### ISSUE THREAD

**Issue by jdahdah** [readwiseio/obsidian-readwise#11]
Hey! Would it be possible for the plugin to download the cover images instead of linking them to a CDN? One of the of core values of Obsidian is being able to keep your notes for life (quote: _"Notes for your grandchildren"_). It would be great if you could enable this as an option so that my Obsidian notes don't need to rely on external sources that won't be around forever.

**Comment by tadeoos** [comment]
Hey, we're not planning to implement this ourselves, but we recommend checking out https://github.com/aleksey-rezvov/obsidian-local-images plugin for that :)
