### ISSUE TITLE
Plugin does not work on mobile yet

### ISSUE THREAD

**Issue by radzio** [readwiseio/obsidian-readwise#2]
Would be great if this coulld work on mobile devices(like iPad) too.

Existing not official plugins work on iPad, so there should not be any technical obstacles.

![image](https://user-images.githubusercontent.com/469111/128763403-31308af0-189d-4635-a8fb-0a9847e73f88.png)

**Comment by TristanH** [comment]
Hey @radzio! It's definitely on the roadmap to have iOS/Android support.

Indeed, we haven't even "launched" this integration yet, we just wanted it to get it into the store before launching and having it fully ready for users :P

**Comment by radzio** [comment]
Can't wait :) 

<img src="https://media3.giphy.com/media/xxAsO5MtariRW/200.gif?" cid=5a38a5a2m5ok1i0mkl8igd5hoi0u3yubohoh6tdxdoml01c3&rid=200.gif&ct=g" />

**Comment by Dovizu** [comment]
Also excited for mobile integration to work 🙂

**Comment by tadeoos** [comment]
I'm gladly closing this as we are now supporting mobile as of v2.0.0 :)

thanks all for your patience!
