### ISSUE TITLE
The CJK file name is unreadable

### ISSUE THREAD

**Issue by taiansu** [readwiseio/obsidian-readwise#3]
The official plugin use `normalizePath` to generate file name (at [here](https://github.com/readwiseio/obsidian-readwise/blob/master/main.ts#L243)), which will romanize the CJK file names and basically make them become noise instead of information.

Here is the screenshot showing the difference of synced file names from the official plugin and the community one.

<img width="480" alt="截圖 2021-08-11 02 23 25" src="https://user-images.githubusercontent.com/241597/128918045-3847f04d-66de-4ea0-81dc-96e2ad3b44b6.png">

So in the community plugin, it simply [sanitize the name using some regular expressions](https://github.com/renehernandez/obsidian-readwise/blob/main/src/fileDoc.ts#L46-L62), but not nomalize it.

**Comment by lishid** [comment]
Just want to update here that `normalizePath` is internally used throughout Obsidian so it shouldn't romanicize CJK or anything - it only converts `\` to `/` and normalizes Unicode representation to NFC form. CJK characters should be left as-is.

**Comment by tadeoos** [comment]
@taiansu thanks a lot for reporting this!
In the end, it wasn't about the `normalizePath` function — we do some title sanitization before we even send data to Obsidian. As you pointed out — it was definitely lacking :)

It's now fixed. If you delete your `Readwise` base folder in Obsidian and trigger the sync again, you should be seeing the correct file names.

Let me know if this is not the case!
