### ISSUE TITLE
not syncing correctly from readwise to obsidian

### ISSUE THREAD

**Issue by ronamosa** [readwiseio/obsidian-readwise#30]
Hi,

when I syn from my readwise account to Obsidian, all of my documents land in the `Readwise\Articles` folder (no other folders are created as per the Export preferences).

When I check the synced articles Metadata, they show `#articles` even though the metadata in readwise clearly says e.g. `#tweet`. 

I am using Obsidian v1.1.9 if that helps.

**Comment by writtenfool** [comment]
Have you toggled the "Group Files in Category Folders" option on the Readwise Export page?
