### ISSUE TITLE
Add support for highlight ids

### ISSUE THREAD

**Issue by radzio** [readwiseio/obsidian-readwise#4]
Would be great if the official Readwise plugin would support block-level link references (using the Highlight ID) just like https://github.com/jsonMartin/readwise-mirror#features plugin

![image](https://user-images.githubusercontent.com/469111/129001180-3f733706-e3c4-48bc-943b-f5c1a1f3a0a3.png)

I did not found highlight id in the doc https://help.readwise.io/article/126-how-can-i-customize-the-readwise-to-obsidian-export#highlight

**Comment by TristanH** [comment]
Yep! Shouldn't be too hard :) Coming soon...

**Comment by tadeoos** [comment]
Hey @radzio!

I've just added the highlight id to template variables and as a bonus, I added the date highlight was taken as well ;)

<img width="486" alt="Screenshot 2021-08-12 at 11 54 53" src="https://user-images.githubusercontent.com/10894783/129177422-1da4ce3c-1d6c-471a-8e78-a8e3da5398f3.png">
