### ISSUE TITLE
Duplicate content when using nested custom folder

### ISSUE THREAD

**Issue by rviljoen** [readwiseio/obsidian-readwise#5]
When setting the base folder as a nested folder (e.g. "Literature notes\Readwise"), each export appends the full Readwise highlight to the bottom of the existing note, i.e. not only changes / additions. When setting the base folder to a non-nested folder (e.g. "Test"), then the sync works fine.

**Comment by rviljoen** [comment]
I have managed to narrow down the problem. Running on Mac, when using "Literature notes\Readwise" the sync files are written to the correct folder, but each sync appends the full contents of the Readwise highlights. When using "Literature notes/Readwise" instead, the sync works correctly. May be a good idea to replace \'s during configuration, or warn the user to use /'s instead.

**Comment by tadeoos** [comment]
Hey @rviljoen! Thanks a lot for reporting this! Just released version 1.0.5 with an improved validation for this setting :)
