### ISSUE TITLE
Allow customisation of the filename

### ISSUE THREAD

**Issue by jamiemchale** [readwiseio/obsidian-readwise#6]
I'd like to be able to customise the filename (and therefore title) of the note that is generated by Readwise.

A reason for this is that I have general book notes (literature notes) that summarise books, but I'd like to be able to link through to the highlights that Readwise has captured (either link or block-ref). Having two notes with the same title in the Obsidian vault can be confusing. I'd like to title it "Highlights from How to Take Smart Notes" rather than "How to take Smart Notes".

🙏

**Comment by TristanH** [comment]
@jamiemchale definitely! We've had quite a few requests for this, and so we have it on our roadmap :)

**Comment by tadeoos** [comment]
@jamiemchale I'm happy to tell you this is now possible at https://readwise.io/export/obsidian/preferences :)

**Comment by jamiemchale** [comment]
Great work! Thank you!
