### ISSUE TITLE
v2.1.0 is incompatible with iOS/iPadOS devices

### ISSUE THREAD

**Issue by marcus-crane** [readwiseio/obsidian-readwise#70]
Hey there,

I upgraded to the latest version of the plugin and was surprised to find that it failed to load both on my iPad Air and iPhone.

After some digging, I've discovered that while the codebase has long had a call to `process.env`, as part of building the base URL, it had been optimised out of the final release.

*Snippet from main.js in v2.0.1*
![IMG_0099](https://github.com/user-attachments/assets/2b80017b-8d3c-467b-bc33-5406f7f1f05a)

*Snippet from main.js in v2.1.0*
![IMG_0098](https://github.com/user-attachments/assets/2f53079f-ee35-4b04-bad1-c2810f70ec79)

With the addition of a new Github Actions workflow, this call is now included which makes the plugin fail to load on iOS/iPadOS due to the `process` API not being available on those devices.

**Comment by tadeoos** [comment]
Thanks so much for reporting this and finding the root cause!
I just released 2.1.1 — please let me know if it works correctly for you now

**Comment by marcus-crane** [comment]
Super fast! I can confirm that it's working again for iOS and iPadOS 🙂
